config/routes.rb
BitFlow::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions', :passwords => 'passwords', :unlocks => 'unlocks'  } 

  resources :fund_withdraw_requests
  resources :usd_fund_transaction_details
  resources :btc_withdraw_requests
  resources :user_wallets
  resources :fund_deposit_requests
  resources :users, :only => [:show, :update]
  
  resources :bankaccounts, :only => [:index, :new, :create, :destroy]
  resources :asks, :except => [:edit, :update]
  resources :bids, :except => [:edit, :update]
  resources :orders, :only => [:index, :new]
  resources :trades, :only => [:index, :show] do
    collection do
      get 'price_graph'
      get 'market_price'
    end
  end
  
  match '/faq' => "home#faq"
  match '/about_us' => "home#about_us"
  match '/contact_us' => "home#contact_us"
  match '/latest_updates' => "home#latest_updates"
  match '/trading_api' => "home#trading_api"
  match '/affiliate_program' => "home#affiliate_program"
  match '/terms_of_use' => "home#terms_of_use"
  match '/privacy_policy' => "home#privacy_policy"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end

  match '/signin_help' => 'home#signin_help'

  resources :welcome, :only => [:index]

  root :to => "home#index"

  namespace :admin do
    root :to => 'settings#edit'
    match '/signin_help' => 'home#signin_help'
    match 'fund_deposit_requests/search' => 'fund_deposit_requests#search', :via => :post
    resources :funds, :only => [:index], :controllers => 'funds'
    resources :orders, :only => [:index, :show], :controllers => 'orders'
    resources :trades, :only => [:index, :show], :controllers => 'trades'
    resources :fund_deposit_requests, :only => [:index, :update, :show, :edit], :controllers => 'admin/fund_deposit_requests'
    resources :search_criterias, :controllers => 'admin/fund_deposit_requests'
    match 'settings/update' => 'settings#update', :via => :post
    resources :fund_withdraw_requests, :only => [:index, :update, :show, :edit], :controllers => 'admin/fund_withdraw_requests'
  end

  match '/v1/balance' => 'api/trade_api#balance'
  match '/v1/orders' => 'api/trade_api#orders'

end

app/views/shared/_authenticated_menu_items.html.haml
- if user_signed_in? && !(current_page?(new_bid_url) || current_page?(new_ask_url)) && !current_user.admin?
  %div
    %ul.authenitcated-menu
      %li= link_to 'Buy Bitcoins', new_bid_url(:type => :limit)
      %li= link_to 'Sell Bitcoins', new_ask_url(:type => :limit)

app/views/shared/_greenbar.html.haml
- if !current_user
  #homeheader
    #left-column
      %h2 Welcome to BitFlow.
      %p Here you can trade bitcoins and use your wallet, which by the way, you can always audit on Blockexplorer.
      %p
        %span.learnmore
          %a{:href => "#nogo"} Learn More
    #right-column
      %h2 In the spotlight
      %ul#portfolio
        %li
          .imgholder
            %img{:alt => "Ubuntu", :height => "155", :src => "images/ubuntu.gif", :width => "172"}/
          .txtholder
            %h3 Low fees
            %p Fixed low fees.
            %span.button-small
              %a{:href => "#"} Learn More
        %li
          .imgholder
            %img{:alt => "Ubuntu", :height => "155", :src => "images/firefox.gif", :width => "172"}/
          .txtholder
            %h3 Single-address wallets
            %p Your wallet consists of a single address, whch means you can audit all your transactions on Blockexplorer.
            %span.button-small
              %a{:href => "#"} Learn More
        %li
          .imgholder
            %img{:alt => "SC", :src => "images/x/startupchile.jpg", :width => "172"}/
          .txtholder
            %h3 Startup Chile 2011...
            %p We are proud participants in the Startup Chile 2011 program.
            %span.button-small
              %a{:href => "http://www.startupchile.org/"} Learn More

app/views/shared/_market_price_ticker.html.haml
.market_price_ticker{title: "Market Price"}
  %div
    #{ @last_trade.try(:market_price).try(:round, 2) }

app/views/shared/_navigation.html.haml
%ul
  = nav_link_to_current 'Trade', root_url
  = nav_link_to_current 'My Wallet', user_wallets_url
  = nav_link_to_current 'Settings', welcome_index_url
  = nav_link_to_current 'Support', welcome_index_url

app/views/shared/_order_book.html.haml
#user-order-book
  %table
    %caption
      %em My Order Book
    %thead
      %tr
        %th Last updated at
        %th Type
        %th Offered
        %th Asked
        %th Limit Price        
        %th.last 
    %tbody
      - orders.each do |order|
        %tr{class: cycle("odd", "even")}
          %td #{order["updated_at"]}
          %td Limit #{order["type"]}
          %td #{order['type'].downcase == 'ask'? "#{order['amount_remaining'].to_f} BTC" : "#{order['total_price'].to_f} USD"}
          %td #{order['type'].downcase == 'ask'? "#{order['total_price'].to_f} USD" : "#{(order['amount_remaining']).to_f} BTC"}
          %td #{order["price"].to_f}          
          %td= link_to('Cancel', "/#{order["type"].downcase}s/#{order["id"]}", method: :delete, confirm: "Are you sure to cancel this #{order["type"]}?")
      %tr{class: cycle("odd", "even")}
        %td{colspan: 7, class: "more"}= link_to 'more...', orders_url

app/views/shared/_sidebar.html.haml
%ul#menu
  - if current_user.try(:admin?)
    %li= link_to_current 'Settings[Admin]', admin_root_url
    %li= link_to_current 'Funds[Admin]', admin_funds_url
    %li= link_to_current 'Manage Fund Deposits[Admin]', admin_fund_deposit_requests_url
    %li= link_to_current 'Manage Fund Withdrawals[Admin]', admin_fund_withdraw_requests_url
    %li= link_to_current 'Orders[Admin]', admin_orders_url
    %li= link_to_current 'Trades[Admin]', admin_trades_url
  %li= link_to_current 'Home', root_url
  %li= link_to_current 'Dashboard', welcome_index_url
  %li= link_to_current 'My Wallet', user_wallets_url
  / %li= link_to_current 'BTC Fixed Mining'
  / %li= link_to_current 'BTC Mining Contract'
  %li= link_to_current 'Deposit Funds', fund_deposit_requests_url
  %li= link_to_current 'Withdraw Funds', fund_withdraw_requests_url
  %li= link_to_current 'Manage Bank Accounts', bankaccounts_url
  = yield(:sidebar)

app/views/shared/_topright.html.haml
.bracket-end

#intro
  - unless current_user
    %p
      %strong Bitcoin
      is the world's first peer-to-peer digital money based on cryptography. Simplicity, security and anonimity (if used correctly) make Bitcoin a viable alternative for internet payments. 
      %br/
      %img{:alt => "link", :height => "10", :src => "images/greenbullet.gif", :width => "10"}/
      %a{:href => "http://www.weusecoins.com/"} Learn More
      |
      %a{:href => "/users/sign_up"}
        %strong Register
      |
      %a{:href => "/users/sign_in"} Login
  - else
    %p
      = render '/devise/shared/login_items'
      %br/
      - address = current_user.user_wallet.address
      %a{:href => "http://blockexplorer.com/address/#{address}"}
        #{address}
      %strong= current_user.btc.available
      BTC
      |
      %strong= current_user.usd.available
      USD
      %br/
      %span.button-small= link_to 'Send BTC', new_btc_withdraw_request_path
      %span.button-small= link_to 'Buy BTC', new_bid_path
      %span.button-small= link_to 'Sell BTC', new_ask_path

app/views/shared/_trade_logs.html.haml
#user-trade-book
  %table
    %caption
      %em My Trade Log
    %thead
      %tr
        %th Executed at
        %th Type        
        %th Sold
        %th Bought
        %th Limit Price
        %th.last New Market Price
    %tbody
      - trades.each do |trade|
        %tr{class: cycle("odd", "even")}
          %td #{trade['executed_at']}
          %td Limit #{trade['type']}          
          %td #{trade['type'].downcase == 'ask'? "#{trade['sold'].to_f} BTC" : "#{trade['sold'].to_f} USD"}
          %td #{trade['type'].downcase == 'ask'? "#{trade['bought'].to_f} USD" : "#{trade['bought'].to_f} BTC"}
          %td #{trade["price"].to_f}
          %td #{trade["execution_price"].to_f} 
      - if snapshot
        %tr{class: cycle("odd", "even")}
          %td{colspan: 7, class: "more"}= link_to 'more...', trades_url

app/views/shared/_whitebar.html.haml
- if !current_user
  #col1
    %h2 Low fees
    %p Fixed low fees.
  #col2 
    %h2 More to come
    %p Expect unique Bitcoin-tailored financial instruments in the near future!
  #col3
    %h2 Single-address wallets
    %p Your wallet consists of a single address, whch means you can audit all your transactions on Blockexplorer.