config/routes.rb
BitFlow::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions', :passwords => 'passwords', :unlocks => 'unlocks'  } 

  resources :fund_withdraw_requests
  resources :usd_fund_transaction_details
  resources :btc_withdraw_requests
  resources :user_wallets
  resources :fund_deposit_requests
  resources :users, :only => [:show, :update]
  
  resources :bankaccounts, :only => [:index, :new, :create, :destroy]
  resources :asks, :except => [:edit, :update]
  resources :bids, :except => [:edit, :update]
  resources :orders, :only => [:index, :new]
  resources :trades, :only => [:index, :show] do
    collection do
      get 'price_graph'
      get 'market_price'
    end
  end
  
  match '/faq' => "home#faq"
  match '/about_us' => "home#about_us"
  match '/contact_us' => "home#contact_us"
  match '/latest_updates' => "home#latest_updates"
  match '/trading_api' => "home#trading_api"
  match '/affiliate_program' => "home#affiliate_program"
  match '/terms_of_use' => "home#terms_of_use"
  match '/privacy_policy' => "home#privacy_policy"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end

  match '/signin_help' => 'home#signin_help'

  resources :welcome, :only => [:index]

  root :to => "home#index"

  namespace :admin do
    root :to => 'settings#edit'
    match '/signin_help' => 'home#signin_help'
    match 'fund_deposit_requests/search' => 'fund_deposit_requests#search', :via => :post
    resources :funds, :only => [:index], :controllers => 'funds'
    resources :orders, :only => [:index, :show], :controllers => 'orders'
    resources :trades, :only => [:index, :show], :controllers => 'trades'
    resources :fund_deposit_requests, :only => [:index, :update, :show, :edit], :controllers => 'admin/fund_deposit_requests'
    resources :search_criterias, :controllers => 'admin/fund_deposit_requests'
    match 'settings/update' => 'settings#update', :via => :post
    resources :fund_withdraw_requests, :only => [:index, :update, :show, :edit], :controllers => 'admin/fund_withdraw_requests'
  end

  match '/v1/balance' => 'api/trade_api#balance'
  match '/v1/orders' => 'api/trade_api#orders'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    @bids = Bid.active.highest.all(:limit => 5)
    @asks = Ask.active.lowest.all(:limit => 5)
  end

  def about_us; end
  
  def faq; end
  def contact_us; end

  def terms_of_use; end
  def privacy_policy; end
  def latest_updates; end
  def trading_api; end
  def affiliate_program; end
end

app/helpers/home_helper.rb
module HomeHelper
	def referral_code
		if current_user.nil?
			''
		else
			'Referral Code: ' + current_user.referral_code
		end
	end

	def referral_code_link
		if current_user.nil?
			''
		else
			'Referral Code link: ' + request.url + 'users/sign_up?referrer_code=' + current_user.referral_code
		end
	end

end

app/views/home/_order_books.html.haml
%table
  %caption
    %em #{item_type}s Order Book
  %thead
    %tr
      %th #{item_type}s
      %th.last Amount
  %tbody
    - items.each do |item|
      %tr{:class => cycle("odd", "even")}
        %td #{item.price}
        %td #{item.amount} BTC

app/views/home/_recent_orders.html.haml
%table
  %caption
    %em #{item_type}s Order Book
  %thead
    %tr
      %th #{item_type}s
      %th.last Amount
  %tbody
    - items.each do |item|
      %tr{:class => cycle("odd", "even")}
        %td #{item.price}
        %td #{item.amount_remaining} BTC

app/views/home/about_us.html.haml
%center
  %h1 About Us
  %hr
%h2  The Bitflow founder team consists of 5 people
%ul
  %li Peter - Jan(PJ),CEO
  %li Jure, CTO
  %li Nila, Developer
  %li Niket, Developer
  %li Sreekanth, Developer

app/views/home/affiliate_program.html.haml
%center
  %h1 BitFlow Affiliate Program
  %hr
%p Every BitFlow user receives a referral code and referral link that he or she can use to refer friends to our service.The referral link will automatically fill in your referral code in the signup form when it is clicked upon by the visitors you refer to our site.
%p
%p When logged in,you will find your referral code and referral link in the "Home" tab.
%p
%p Everybody who signs up using a referral code gets 10% off commissions for life.You earn 10% of all the applicable commissions generated by your referral users.
%p
%p Our affiliated programs covers both BTC trading(instant,market,limit orders) and Mining Trading(fixing mining,mining contracts).For BTC instant orders,which has commission rates depending.

app/views/home/contact_us.html.haml
%p
  %h2  Contact Us
  %hr
%p 1.Nilakanta Mallick  ---- +91 80 28495559
%p 2.Nikhet             ---- +91 9999999999

app/views/home/faq.html.haml
%center
  %h2 FAQ
  %hr
%h4 Please note that this page covers only the most frequently asked questions about BitFlow and BitCoins in general.
%br/
%h4 To acces our full Helpdesk and Mail Support, please click the "Feedback & Support" icon at the bottom right of this page.
%br/
%h3 BitFlow FAQ
%ul
  %li
    %a{:href => '#answer-1'} Question 1?
  %li
    %a{:href => '#answer-1'} Question 2?
%br
%h3 BitCoin FAQ Answers
%ul
  %li#answer-1 Answer 1
  %li#answer-2 Answer 2

app/views/home/index.html.erb
Hello World

app/views/home/index.html.haml
/ %ul.span-14
/  - if current_user
/    %li= referral_code
/    %li= referral_code_link
/  %li Lowest Commissions (0.3%)
/  %li Dedicated BTC Wallet
/  %li Trade BTC & Mining Contracts
/  %li
/    Earn interest with
/    = link_to 'Fixed Mining', '/fixed_mining'
/%hr

- content_for(:nav) do
  = render '/shared/navigation'
- content_for(:homeheader) do
  = render '/shared/greenbar'
= render '/shared/whitebar'

.divider

#tabs
  %ul
    %li
      %a{:href => '#btc'} BTC
  #btc
    #btc_pricing_graph

- content_for(:sidebar) do
  #recent-order-books
    .bids= render :partial => 'recent_orders', :locals => {:items => @asks, :item_type => 'Ask'}
    .asks= render :partial => 'recent_orders', :locals => {:items => @bids, :item_type => 'Bid'}

- content_for(:javascript) do  
  = javascript_include_tag 'highstock.src'

  :javascript
    $(function() {
      $('#tabs').tabs();
      loadPriceChart();
    });
  

app/views/home/latest_updates.html.haml
%center
  %h1 Latest Updates
  %hr
01/01/2012: BitFlow now has 20 employees who make a ton of profit share each! 
%br
10/08/2011: Final 1.0 now launched!
%br
01/08/2011: We launch beta real limit order trading with interview on The Bitcoin Show live from India (PJ visits for a week)
%br
25/07/2011: Alpha is finished!
%br
11/07/2001: The upfront payments are made!
%br
11/07/2011: The mockups are finished!

app/views/home/privacy_policy.html.haml
%center
  %h1 Privacy Policy
  %hr

The privacy policy of BitFlow come here.
%br 
It will be just plain text.
%br 
We will start with the sample Trust Guard generates.
%br 
Later on we'll pay a specialized law firm to write one.

app/views/home/signin_help.html.haml
%h4 Forgot Password?
%p
  If you have forgotten your password, click #{link_to "here", new_password_path(resource_name)}.

%h4 Account locked?
%p
  If your account has been locked, please click #{link_to "here", new_unlock_path(resource_name)}.

%h4 Confimation pending?
%p
  Please remember to confirm the account within #{Devise.confirm_within.inspect}. If you would like to receive the confirmation email again, click #{link_to "here", new_confirmation_path(resource_name)}.

app/views/home/terms_of_use.html.haml
%center
  %h1 Terms Of Use
  %hr

%p The terms of use of BitFlow come here.
%br/
%p It will be just plain text.
%br/
%p I'll start with paraphrasing other terms and conditions.
%br/
%p Later on we'll pay a specialized law firm to write one.
%br/
%p Terms of use need to mention:
%ul
  %li Changes we made to keep btw wallet fixed
  %li Limitation of liability
  %li User responsible to check legality in home jurisdiction
  %li Full authority to change terms of use
  %li Full authority to stop trading and cancel trades
  
      

app/views/home/trading_api.html.haml
%center
  %h1 Trading API
  %hr
%p The BitFlow Trading API allows developers to build applications that directly interact with our market place. 
%br/
%p Potential uses include data aggregation, market arbitrage, mobile clients, etcetera.
%br/
%p Public Data Functions:
%ul 
%li Orderbook: (link)
%li Trades log: (link)
%li Price ticker: (link)
%li Trading Functions:(see Tradehill)
  



  