config/routes.rb
BitFlow::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions', :passwords => 'passwords', :unlocks => 'unlocks'  } 

  resources :fund_withdraw_requests
  resources :usd_fund_transaction_details
  resources :btc_withdraw_requests
  resources :user_wallets
  resources :fund_deposit_requests
  resources :users, :only => [:show, :update]
  
  resources :bankaccounts, :only => [:index, :new, :create, :destroy]
  resources :asks, :except => [:edit, :update]
  resources :bids, :except => [:edit, :update]
  resources :orders, :only => [:index, :new]
  resources :trades, :only => [:index, :show] do
    collection do
      get 'price_graph'
      get 'market_price'
    end
  end
  
  match '/faq' => "home#faq"
  match '/about_us' => "home#about_us"
  match '/contact_us' => "home#contact_us"
  match '/latest_updates' => "home#latest_updates"
  match '/trading_api' => "home#trading_api"
  match '/affiliate_program' => "home#affiliate_program"
  match '/terms_of_use' => "home#terms_of_use"
  match '/privacy_policy' => "home#privacy_policy"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end

  match '/signin_help' => 'home#signin_help'

  resources :welcome, :only => [:index]

  root :to => "home#index"

  namespace :admin do
    root :to => 'settings#edit'
    match '/signin_help' => 'home#signin_help'
    match 'fund_deposit_requests/search' => 'fund_deposit_requests#search', :via => :post
    resources :funds, :only => [:index], :controllers => 'funds'
    resources :orders, :only => [:index, :show], :controllers => 'orders'
    resources :trades, :only => [:index, :show], :controllers => 'trades'
    resources :fund_deposit_requests, :only => [:index, :update, :show, :edit], :controllers => 'admin/fund_deposit_requests'
    resources :search_criterias, :controllers => 'admin/fund_deposit_requests'
    match 'settings/update' => 'settings#update', :via => :post
    resources :fund_withdraw_requests, :only => [:index, :update, :show, :edit], :controllers => 'admin/fund_withdraw_requests'
  end

  match '/v1/balance' => 'api/trade_api#balance'
  match '/v1/orders' => 'api/trade_api#orders'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @orders = Order.non_executed(current_user)
    @trades = Order.executed(current_user)
    @funds = Fund.where(:user_id => current_user.id)
  end

end

app/views/welcome/_fund.html.haml
#user-funds
  %table
    %caption
      %em My Funds
    %thead
      %tr
        %th Type
        %th Amount
        %th Reserved
        %th Available
        %th.last History
    %tbody
      - funds.each do |fund|
        %tr{class: cycle("odd", "even")}
          %td #{fund["fund_type"]}
          %td #{fund["amount"].to_f}
          %td #{fund["reserved"].to_f} 
          %td #{fund["available"].to_f}
          - if fund["fund_type"] == 'BTC'
            %td= link_to "BTC Fund History", user_wallets_url
          - if fund["fund_type"] == 'USD'
            %td= link_to "USD Fund History", usd_fund_transaction_details_url

app/views/welcome/_order_book.html.haml
#user-order-book
  %table
    %caption
      %em Non-executed Limit Orders in Order Book
    %thead
      %tr
        %th Last updated at
        %th Type
        %th Price
        %th Amount
        %th Status
        %th.last Commission
    %tbody
      - orders.each do |order|
        %tr{class: cycle("odd", "even")}
          %td #{order["updated_at"]}
          %td #{order["type"]}
          %td #{order["price"].to_f}
          %td #{order["amount"].to_f} 
          %td #{order["status"]} 
          %td 0.25 USD
      %tr{class: cycle("odd", "even")}
        %td{colspan: 7, class: "more"}= link_to 'more...', orders_url

app/views/welcome/_trade_book.html.haml
#user-trade-book
  %table
    %caption
      %em Executed Orders in Order Book
    %thead
      %tr
        %th Executed at
        %th Sold
        %th Bought
        %th Bid/Ask Price
        %th Price per BTC
        %th Commission
    %tbody
      - trades.each do |trade|
        %tr{class: cycle("odd", "even")}
          %td #{trade['executed_at']}
          %td #{trade["sold"].blank? ? '' : trade["sold"].to_f}
          %td #{trade["bought"].blank? ? '' : trade["bought"].to_f}
          %td #{trade["price"].to_f} 
          %td #{trade["execution_price"].to_f} 
          %td 0.25 USD
      %tr{class: cycle("odd", "even")}
        %td{colspan: 6, class: "more"}= link_to 'more...', orders_url

app/views/welcome/index.html.haml
= render partial: 'fund', locals: {funds: @funds}
= render partial: 'shared/order_book', locals: {snapshot: true, orders: @orders}
= render partial: 'shared/trade_logs', locals: {snapshot: true, trades: @trades}